var maps = {
  map_00: { "height":16,
   "infinite":false,
   "layers":[
          {
           "data":[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 12, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 8, 8, 8, 2, 2, 12, 5, 2, 2, 8, 8, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 8, 2, 2, 2, 5, 12, 5, 5, 2, 2, 2, 8, 2, 2, 2, 2, 2, 5, 4, 12, 12, 2, 12, 12, 8, 2, 2, 5, 5, 4, 4, 5, 5, 2, 2, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 12, 2, 2, 2, 5, 5, 4, 6, 6, 4, 5, 5, 2, 12, 2, 2, 2, 12, 12, 12, 4, 5, 5, 5, 12, 5, 5, 5, 5, 4, 6, 6, 6, 6, 4, 5, 5, 12, 5, 5, 5, 12, 5, 5, 9, 5, 5, 5, 12, 5, 5, 5, 5, 4, 6, 6, 6, 6, 4, 5, 5, 12, 5, 5, 5, 12, 5, 5, 9, 2, 2, 2, 12, 2, 2, 2, 5, 5, 4, 6, 6, 4, 5, 5, 2, 12, 2, 2, 2, 12, 2, 5, 4, 12, 12, 12, 12, 12, 8, 2, 2, 5, 5, 4, 4, 5, 5, 2, 2, 8, 2, 2, 2, 12, 2, 5, 4, 2, 2, 2, 2, 2, 8, 2, 2, 2, 5, 5, 5, 5, 2, 2, 2, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 8, 8, 8, 2, 2, 5, 5, 2, 2, 8, 8, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 2, 12, 2, 2, 2, 5, 5, 2, 2, 2, 12, 2, 2, 2, 2, 2, 2, 5, 4, 5, 5, 5, 5, 5, 5, 12, 5, 5, 5, 5, 5, 5, 5, 5, 12, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
           "height":16,
           "id":2,
           "name":"Tile Layer 1",
           "opacity":1,
           "type":"tilelayer",
           "visible":true,
           "width":24,
           "x":0,
           "y":0
          }, 
          {
           "draworder":"topdown",
           "id":4,
           "name":"Object Layer 1",
           "objects":[
                  {
                   "height":16,
                   "id":4,
                   "name":"player",
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":0,
                   "y":128
                  }, 
                  {
                   "height":16,
                   "id":5,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":18
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":32,
                   "y":48
                  }, 
                  {
                   "height":16,
                   "id":7,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":20
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_lance"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":112,
                   "y":96
                  }, 
                  {
                   "height":16,
                   "id":8,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":30
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-5
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":0,
                   "y":176
                  }, 
                  {
                   "height":16,
                   "id":9,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":18
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":176,
                   "y":192
                  }, 
                  {
                   "height":16,
                   "id":10,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":20
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_lance"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":240,
                   "y":32
                  }, 
                  {
                   "height":16,
                   "id":11,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":18
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":288,
                   "y":160
                  }, 
                  {
                   "height":16,
                   "id":12,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":18
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":336,
                   "y":112
                  }],
           "opacity":1,
           "type":"objectgroup",
           "visible":true,
           "x":0,
           "y":0
          }],
   "nextlayerid":5,
   "nextobjectid":13,
   "orientation":"orthogonal",
   "renderorder":"right-down",
   "tiledversion":"1.2.0",
   "tileheight":16,
   "tilesets":[
          {
           "firstgid":1,
           "source":"tileset.json"
          }],
   "tilewidth":16,
   "type":"map",
   "version":1.2,
   "width":24
  },
  map_01:{ "height":24,
   "infinite":false,
   "layers":[
          {
           "data":[14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 4, 4, 4, 4, 4, 4, 4, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 4, 16, 16, 16, 16, 16, 4, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 14, 14, 16, 16, 16, 16, 16, 16, 16, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 16, 16, 16, 16, 16, 16, 16, 14, 14, 14, 14, 15, 14, 14, 15, 14, 14, 14, 15, 14, 14, 14, 14, 14, 15, 15, 14, 14, 14, 14, 14, 14, 4, 16, 16, 16, 16, 16, 4, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 15, 15, 14, 14, 14, 14, 14, 14, 14, 4, 4, 4, 4, 4, 4, 4, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 2, 2, 8, 8, 8, 2, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 14, 2, 2, 6, 6, 6, 6, 6, 2, 8, 8, 4, 4, 4, 17, 4, 4, 4, 4, 16, 16, 4, 4, 14, 14, 14, 14, 14, 14, 15, 15, 14, 14, 2, 6, 6, 6, 6, 6, 6, 6, 2, 14, 4, 16, 16, 16, 16, 16, 4, 4, 16, 16, 4, 4, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 2, 6, 6, 6, 6, 6, 6, 6, 2, 14, 4, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 4, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 2, 6, 6, 6, 6, 6, 6, 6, 2, 14, 4, 16, 4, 4, 4, 16, 4, 4, 16, 16, 4, 4, 14, 14, 14, 15, 15, 15, 14, 14, 14, 14, 2, 6, 6, 6, 6, 6, 6, 6, 2, 14, 4, 16, 16, 4, 16, 16, 4, 16, 16, 16, 16, 4, 14, 14, 14, 14, 14, 14, 15, 15, 15, 14, 2, 6, 6, 6, 6, 6, 6, 6, 2, 14, 4, 16, 16, 4, 16, 16, 4, 4, 16, 16, 4, 4, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 2, 2, 6, 6, 6, 6, 2, 2, 14, 4, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 14, 2, 2, 2, 2, 2, 2, 14, 14, 4, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 4, 16, 16, 4, 4, 4, 4, 4, 4, 17, 4, 4, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 4, 16, 16, 16, 4, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 15, 14, 14, 4, 16, 19, 16, 4, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 14, 14, 4, 16, 16, 16, 4, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 14, 14, 14, 4, 16, 16, 16, 4, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 15, 15, 14, 14, 14, 15, 15, 14, 14, 14, 14, 4, 16, 16, 16, 4, 14, 14, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 16, 16, 16, 16, 4, 14, 14, 14, 15, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 16, 16, 16, 16, 4, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 4, 4, 4, 4, 4],
           "height":24,
           "id":1,
           "name":"Tile Layer 1",
           "opacity":1,
           "type":"tilelayer",
           "visible":true,
           "width":32,
           "x":0,
           "y":0
          }, 
          {
           "draworder":"topdown",
           "id":2,
           "name":"Object Layer 1",
           "objects":[
                  {
                   "height":16,
                   "id":1,
                   "name":"player",
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":16,
                   "y":32
                  }, 
                  {
                   "height":16,
                   "id":2,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":9
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_lance"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":368,
                   "y":64
                  }, 
                  {
                   "height":16,
                   "id":3,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":12
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-4
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"wind"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":64,
                   "y":112
                  }, 
                  {
                   "height":16,
                   "id":4,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":20
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":48,
                   "y":368
                  }, 
                  {
                   "height":16,
                   "id":5,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":12
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_lance"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":224,
                   "y":32
                  }, 
                  {
                   "height":16,
                   "id":6,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":9
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_lance"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":432,
                   "y":32
                  }, 
                  {
                   "height":16,
                   "id":8,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":432,
                   "y":176
                  }, 
                  {
                   "height":16,
                   "id":9,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":464,
                   "y":224
                  }, 
                  {
                   "height":16,
                   "id":10,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-2
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_axe"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":480,
                   "y":176
                  }, 
                  {
                   "height":16,
                   "id":11,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-4
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"wind"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":128,
                   "y":304
                  }, 
                  {
                   "height":16,
                   "id":12,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-4
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"wind"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":224,
                   "y":320
                  }, 
                  {
                   "height":16,
                   "id":13,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":9
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_lance"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":416,
                   "y":256
                  }],
           "opacity":1,
           "type":"objectgroup",
           "visible":true,
           "x":0,
           "y":0
          }],
   "nextlayerid":3,
   "nextobjectid":14,
   "orientation":"orthogonal",
   "renderorder":"right-down",
   "tiledversion":"1.2.0",
   "tileheight":16,
   "tilesets":[
          {
           "firstgid":1,
           "source":"tileset.json"
          }],
   "tilewidth":16,
   "type":"map",
   "version":1.2,
   "width":32
  },
  map_02:{ "height":24,
   "infinite":false,
   "layers":[
          {
           "data":[4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 8, 8, 12, 12, 12, 12, 12, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 16, 16, 4, 2, 8, 8, 8, 2, 2, 2, 8, 2, 12, 5, 5, 5, 12, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 4, 19, 16, 16, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 4, 16, 16, 4, 5, 5, 5, 5, 5, 5, 2, 8, 2, 12, 5, 5, 5, 12, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 4, 4, 4, 4, 6, 6, 6, 6, 6, 5, 5, 8, 8, 12, 12, 5, 12, 12, 2, 5, 5, 4, 16, 16, 16, 4, 2, 2, 2, 2, 2, 2, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 12, 12, 12, 5, 5, 5, 6, 4, 16, 16, 16, 4, 5, 5, 2, 2, 2, 2, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 4, 16, 16, 16, 4, 6, 5, 5, 5, 2, 2, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 4, 16, 16, 16, 4, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 16, 16, 16, 4, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 16, 16, 16, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 16, 16, 16, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 16, 16, 16, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 2, 2, 2, 2, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 16, 16, 16, 4, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 4, 16, 16, 16, 4, 5, 5, 6, 6, 6, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 8, 8, 2, 2, 12, 12, 12, 12, 12, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 8, 2, 2, 12, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 12, 12, 12, 12, 2, 8, 8, 2, 2, 12, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 8, 2, 2, 2, 2, 12, 5, 5, 5, 12, 2, 8, 8, 2, 2, 12, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 5, 5, 5, 5, 12, 2, 8, 8, 2, 2, 12, 12, 12, 12, 12, 2, 2, 2, 8, 8, 8, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 5, 5, 5, 5, 12, 2, 8, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 8, 8, 2, 2, 2, 2, 5, 5, 5, 5, 12, 2, 8, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 5, 5, 5, 12, 2, 8, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 12, 12, 12, 12, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
           "height":24,
           "id":1,
           "name":"Tile Layer 1",
           "opacity":1,
           "type":"tilelayer",
           "visible":true,
           "width":32,
           "x":0,
           "y":0
          }, 
          {
           "draworder":"topdown",
           "id":2,
           "name":"Object Layer 1",
           "objects":[
                  {
                   "height":16,
                   "id":1,
                   "name":"player",
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":48,
                   "y":336
                  }, 
                  {
                   "height":16,
                   "id":2,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":80,
                   "y":272
                  }, 
                  {
                   "height":16,
                   "id":5,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":368,
                   "y":352
                  }, 
                  {
                   "height":16,
                   "id":6,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":368,
                   "y":256
                  }, 
                  {
                   "height":16,
                   "id":7,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":448,
                   "y":304
                  }, 
                  {
                   "height":16,
                   "id":8,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":368,
                   "y":32
                  }, 
                  {
                   "height":16,
                   "id":9,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":2
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-1
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":192,
                   "y":32
                  }],
           "opacity":1,
           "type":"objectgroup",
           "visible":true,
           "x":0,
           "y":0
          }],
   "nextlayerid":3,
   "nextobjectid":10,
   "orientation":"orthogonal",
   "renderorder":"right-down",
   "tiledversion":"1.2.0",
   "tileheight":16,
   "tilesets":[
          {
           "firstgid":1,
           "source":"tileset.json"
          }],
   "tilewidth":16,
   "type":"map",
   "version":1.2,
   "width":32
  },
  map_03: { "height":16,
   "infinite":false,
   "layers":[
          {
           "data":[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 16, 16, 16, 16, 16, 20, 16, 20, 16, 20, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 16, 16, 16, 16, 16, 16, 16, 20, 16, 20, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 16, 16, 16, 16, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 20, 4, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 4, 20, 20, 4, 4, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 4, 4, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 4, 4, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 4, 4, 4, 4, 21, 4, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 4, 21, 21, 4, 4, 4, 4, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 16, 16, 16, 16, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 16, 16, 16, 16, 16, 16, 16, 21, 16, 16, 21, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 16, 16, 16, 16, 16, 16, 16, 21, 16, 16, 21, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
           "height":16,
           "id":1,
           "name":"Tile Layer 1",
           "opacity":1,
           "type":"tilelayer",
           "visible":true,
           "width":24,
           "x":0,
           "y":0
          }, 
          {
           "draworder":"topdown",
           "id":2,
           "name":"Object Layer 1",
           "objects":[
                  {
                   "height":16,
                   "id":1,
                   "name":"player",
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":0,
                   "y":112
                  }, 
                  {
                   "height":16,
                   "id":3,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":24
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":9
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-4
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"thunder"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":32,
                   "y":208
                  }, 
                  {
                   "height":16,
                   "id":4,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":22
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":8
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":208,
                   "y":176
                  }, 
                  {
                   "height":16,
                   "id":5,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":30
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":11
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-6
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":352,
                   "y":16
                  }, 
                  {
                   "height":16,
                   "id":6,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":30
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":11
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":-7
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":6
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"thunder"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":352,
                   "y":224
                  }, 
                  {
                   "height":16,
                   "id":7,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"death_knight",
                           "type":"bool",
                           "value":true
                          }, 
                          {
                           "name":"hp",
                           "type":"int",
                           "value":35
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":30
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":352,
                   "y":128
                  }, 
                  {
                   "height":16,
                   "id":8,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":24
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":9
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":4
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-4
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":32,
                   "y":32
                  }, 
                  {
                   "height":16,
                   "id":9,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":22
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":8
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"steel_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":208,
                   "y":64
                  }],
           "opacity":1,
           "type":"objectgroup",
           "visible":true,
           "x":0,
           "y":0
          }],
   "nextlayerid":3,
   "nextobjectid":10,
   "orientation":"orthogonal",
   "renderorder":"right-down",
   "tiledversion":"1.2.0",
   "tileheight":16,
   "tilesets":[
          {
           "firstgid":1,
           "source":"tileset.json"
          }],
   "tilewidth":16,
   "type":"map",
   "version":1.2,
   "width":24
  }
}
