var maps = {
  map_00: { "height":16,
   "infinite":false,
   "layers":[
          {
           "data":[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 12, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 8, 8, 8, 2, 2, 12, 5, 2, 2, 8, 8, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 8, 2, 2, 2, 5, 12, 5, 5, 2, 2, 2, 8, 2, 2, 2, 2, 2, 5, 4, 12, 12, 2, 12, 12, 8, 2, 2, 5, 5, 4, 4, 5, 5, 2, 2, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 12, 2, 2, 2, 5, 5, 4, 6, 6, 4, 5, 5, 2, 12, 2, 2, 2, 12, 12, 12, 4, 5, 5, 5, 12, 5, 5, 5, 5, 4, 6, 6, 6, 6, 4, 5, 5, 12, 5, 5, 5, 12, 5, 5, 9, 5, 5, 5, 12, 5, 5, 5, 5, 4, 6, 6, 6, 6, 4, 5, 5, 12, 5, 5, 5, 12, 5, 5, 9, 2, 2, 2, 12, 2, 2, 2, 5, 5, 4, 6, 6, 4, 5, 5, 2, 12, 2, 2, 2, 12, 2, 5, 4, 12, 12, 12, 12, 12, 8, 2, 2, 5, 5, 4, 4, 5, 5, 2, 2, 8, 2, 2, 2, 12, 2, 5, 4, 2, 2, 2, 2, 2, 8, 2, 2, 2, 5, 5, 5, 5, 2, 2, 2, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 8, 8, 8, 2, 2, 5, 5, 2, 2, 8, 8, 8, 2, 2, 2, 2, 2, 5, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 12, 2, 2, 2, 2, 2, 2, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 12, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
           "height":16,
           "id":2,
           "name":"Tile Layer 1",
           "opacity":1,
           "type":"tilelayer",
           "visible":true,
           "width":24,
           "x":0,
           "y":0
          }, 
          {
           "draworder":"topdown",
           "id":4,
           "name":"Object Layer 1",
           "objects":[
                  {
                   "height":16,
                   "id":4,
                   "name":"player",
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":(22*16),
                   "y":112
                  }, 
                  {
                   "height":16,
                   "id":5,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":32,
                   "y":48
                  }, 
                  {
                   "height":16,
                   "id":6,
                   "name":"enemy",
                   "properties":[
                          {
                           "name":"hp",
                           "type":"int",
                           "value":10
                          }, 
                          {
                           "name":"level",
                           "type":"int",
                           "value":1
                          }, 
                          {
                           "name":"res_axe",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_fire",
                           "type":"int",
                           "value":5
                          }, 
                          {
                           "name":"res_lance",
                           "type":"int",
                           "value":-3
                          }, 
                          {
                           "name":"res_sword",
                           "type":"int",
                           "value":3
                          }, 
                          {
                           "name":"res_thunder",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"res_wind",
                           "type":"int",
                           "value":0
                          }, 
                          {
                           "name":"weapon",
                           "type":"string",
                           "value":"iron_sword"
                          }],
                   "rotation":0,
                   "type":"",
                   "visible":true,
                   "width":16,
                   "x":112,
                   "y":80
                  }],
           "opacity":1,
           "type":"objectgroup",
           "visible":true,
           "x":0,
           "y":0
          }],
   "nextlayerid":5,
   "nextobjectid":7,
   "orientation":"orthogonal",
   "renderorder":"right-down",
   "tiledversion":"1.2.0",
   "tileheight":16,
   "tilesets":[
          {
           "firstgid":1,
           "source":"tileset.json"
          }],
   "tilewidth":16,
   "type":"map",
   "version":1.2,
   "width":24
  }
}
